_sources/partials.txt, docs/partials.rst, partials.html
Changed gh-pages to show that the property to make an annotation become a partial is *partial*, not *partial_id*
=> Fix partial_id

Readme.md
I grabbed the new release, but the readme had an outdated example. I was getting this error before the change:
```php
( ! ) Notice: Unexpected field "name" for @SWG\Response(), expecting "ref", "response", "description", "schema", "headers", "examples", "x" in 
```
Do the docs need to be updated too? http://zircote.com/swagger-php
What do you think @bfanger?
=> Fixed response annotation example in readme

src/Processors/InheritProperties.php, tests/Fixtures/ChildWithDocBlocks.php, tests/Fixtures/ParentWithoutDocBlocks.php, tests/InheritPropertiesTest.php
If a class inherits from another class without docblocks, swagger-php throws an error, because it is trying to loop through null.
I encountered this problem today. My models inherited from a class without a docblock.
When i tried to run `Swagger\scan('/path/to/app')`, it greeted me with `Invalid argument supplied for foreach()`. Not having DocBlocks in a class is certainly not the best thing to do, but it should not stop me from seeing the swagger generated docs.
I included a unit test with fixtures. If you comment out the `if` statement in `InheritProperties`, you will see, that the unit test fails with said error.
=> Fixed a bug with inherited properties being null

.travis.yml
This PR:
- restructures the current `travis.yml` to use env variables to configure various matrix builds
- does not change the current Travis runs in any way (all PHP version will continue to run phpunit due to the default value for env `PHPUNIT` being set to 1)
The restructure allows for easily adding different specific builds when required. For example, to add a build for only [codecov.io](https://codecov.io) code coverage and thus no phpunit tests one could simply add:
```yml
matrix:
include:
- php: 7.0
env: CODECOVERAGE=1 PHPUNIT=0
script:
- sh -c "if [ '$CODECOVERAGE' = '1' ]; then phpunit --coverage-clover=clover.xml || true; fi"
- sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
- sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; …
```
=> Use env variables for specific Travis matrix builds

src/Util.php
We faced a issue where swagger-php trying to parse non-php files, that causes `Unexpected token error`. I added this patch to our version of swagger-php, to parse only files with .php extensions.
Is there any use case that swagger php needed to parse non-php files?
=> Update finder options to force Swagger-PHP parse only *.php file

.travis.yml, src/Processors/HandleReferences.php, tests/AnalysisTest.php, tests/Fixtures/Ancestor.php, tests/Fixtures/AncestorWithoutDocBlocks.php, tests/Fixtures/Child.php, tests/Fixtures/ChildWithDocBlocks.php, tests/Fixtures/GrandAncestor.php, tests/InheritPropertiesTest.php, tests/UtilTest.php, tests/ValidateRelationsTest.php
I've just fixed 2 of 3 php7cc messages and launched tests under php7.
=> Add php7 compatibility (rename Parent test class), turn on php7 for autotests

docs/Getting-started.md
=> Fix "Unexpected field "descriptions"" error in example

src/StaticAnalyser.php, tests/Fixtures/php7.php, tests/StaticAnalyserTest.php
When parsing my project I got some error output like this
[NOTICE] Uninitialized string offset: 1 in vendor\zircote\swagger-php\src\StaticAnalyser.php on line 93
This resulted from parsing php7 anonymous classes.
I called the new fixture file 'php7.php' so that more php7 specific syntax can be added there in future.
=> Fix errors when parsing php7 anonymous class

bin/swagger
Reflect the fact that you can add more than one path as arguments to the command line runner.
Fixes #379
=> Amend command line runner help message

bin/swagger
Reverts zircote/swagger-php#381 as I missed Travis not having completed yet, tests seemed to fail as well.
=> Revert "Amend command line runner help message"

src/Serializer.php
Hey!
Looks like deserialize was broken with `$ref` field :atom: , example swagger spec
It's `$ref` in JSON scheme, but it's `ref` property inside this library
I am getting a notice "$ref property does not exists", and I am interested to drop hack inside my project:
See: https://github.com/SocialConnect/swagger-codegen/commit/ec274ed6e547ca761f8d47714a8acde4cf0cb7ee
Thank, Have a nice day
=> Serializer - doDeserialize - fix support for $ref

src/StaticAnalyser.php, tests/Fixtures/php7.php
This commit attempts to fix #423 along with additional data in the unit tests to catch this case.
=> Fixes for #423

src/Annotations/Items.php, src/Annotations/Schema.php, tests/ItemsTest.php
According to the spec, when a schema has type `array`, the `items` key must always exist.  This rule was being validated for `@SWG\Items()` but not for all `@SWG\Schema()`.
* Includes a new test to cover the generic `@SWG\Schema()` case.
* Keeps the old test case for `@SWG\Items()` to ensure the log message remained the same.
=> When schema type is array, items key must always exist.

src/Context.php
The phpdoc content is statically parsed (in Context.php). During parsing, the comments are split into an array of lines. Previously, the code used explode("\n", ...) in order to split at Unix (lf) line breaks. In order to also be able to accept Windows/DOS line breaks (cr + lf), explode is replaced by splitting with preg_split on either \n or \r\n.
=> Accept Windows/DOS line breaks in phpdoc summary

src/Annotations/Parameter.php
Hello,
This change ads the Parameter annotation field name allowEmptyValue as this seems to be part of the swagger-php api spec.
https://bfanger.nl/swagger-explained/#parameterObject
Thanks,
Jamie
=> Added field name allowEmptyValue

src/Annotations/AbstractAnnotation.php, src/Annotations/Schema.php, src/Serializer.php, tests/SerializerTest.php
Deserializer work incorrect when we trying to deserialize schema with `allOf` property.
For example allOf properties will be deserialized like `stdClass` with the `$ref` property but according to swagger `allOf,oneOf,anyOf` is array of schemes [link](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/).
Json  string example
```
{
"openapi": "3.0.0",
"info": {
"title": "Pet store",
"version": "1.0"
},
"components": {
"schemas": {
"Dog": {
"allOf": [{
"$ref": "#/components/schemas/SomeSchema"
}]
},
"Cat": {
"allOf": [{
"$ref": "#/components/schemas/SomeSchema"
}]
}
}
}
}
```
The result of deserealization
```
object(OpenApi\Annotations\OpenApi)#2844 (5) {
["openapi"]=>
string(5) "3.0.0"
["info"]=>
object(OpenApi\Annotations\Info)#2848 (4) {
["title"]=>
string(9) "Pet …
```
=> Fix for deserialization of allOf properties

src/functions.php
Hi,
If the `functions.php` file is preloaded and then included at runtime, it triggers a `PHP Fatal error:  Cannot redeclare OpenApi\scan()`.
Constants are not preloaded, so this PR split constants and function definition to fix this issue.
=> PHP 7.4 Preloading: define 'scan()' function only if not already defined

src/functions.php
Hi guys,
same fixes to zircote#748 but for 2.x version
=> PHP 7.4 Preloading: define 'scan()' function only if not already defined for 2.x branch

src/Annotations/Flow.php
The issue reported in #407 and fixed in #408 regressed with the new @OA\Flow keyword.
This annotation:
```
*  @OA\SecurityScheme(
*      type="oauth2",
*      securityScheme="ClientAuth",
*      @OA\Flow(
*          flow="clientCredentials",
*          tokenUrl="/oauth2/token",
*          scopes={},
*      ),
*  ),
```
produces this YAML:
```
securitySchemes:
UserAuth:
type: oauth2
flows:
password:
tokenUrl: /oauth2/token
refreshUrl: /oauth2/token
scopes: []
```
As per the [spec](https://swagger.io/docs/specification/authentication/oauth2/#no-scopes), this should be an empty object, which there isn't a way to directly define with the annotations.
This applies the same fix as #408, but now in the Flow element versus the SecurityScheme element to match OAS3.
With this patch, we get:
``` …
```
=> Apply fix from #407 to this version to fix invalid YAML generated with empty scopes

composer.json, src/Processors/MergeXmlContent.php, tests/MergeJsonContentTest.php, tests/MergeXmlContentTest.php
Adds missing use statements and corresponding test(s).
Also adds `ext-json` as requirement to `composer.json`.
@bfanger sorry for adding nw PRs now that you've cleaned up so nicely.
Feels to me that changes to the repo have been a bit disjointed so there are all sorts of little mismatches. [Also, code coverage is a bit low, IMHO :)]
=> Add missing use statements to MergeXmlContent

tests/Annotations/AbstractAnnotationTest.php, tests/Annotations/AnnotationPropertiesDefinedTest.php, tests/Annotations/ItemsTest.php, tests/Annotations/NestedPropertyTest.php, tests/Annotations/ResponseTest.php, tests/Annotations/SecuritySchemesTest.php, tests/Annotations/ValidateRelationsTest.php, tests/OpenApiTestCase.php, tests/Processors/AugmentOperationTest.php, tests/Processors/AugmentParameterTest.php, tests/Processors/AugmentPropertiesTest.php, tests/Processors/AugmentSchemasTest.php, tests/Processors/BuildPathsTest.php, tests/Processors/CleanUnmergedTest.php, tests/Processors/InheritPropertiesTest.php, tests/Processors/MergeIntoComponentsTest.php, tests/Processors/MergeIntoOpenApiTest.php, tests/Processors/MergeJsonContentTest.php, tests/Processors/MergeXmlContentTest.php
**Changes**
* Mirror the namespaces from `src/` in the `tests/` folder.
* Add some helper methods around fixtures (resolve, load)
* Clarify a couple comments and test names to what I believe they actually do
* Remove redundant dataProvider in favour of shared `OpenApiTestCase::allAnnotationClasses()`
**Motivation**
I've started looking at the current traits support and got really annoyed by the long list of test cases in the `tests` folder itself.
Working my  way backwards through the code I found it hard to see which library classes have corresponding test cases and which not.
Also, before going any further I wanted to see first if my style / thinking is appropriate before committing to more work...
Looking forward I plan on adding more tests first, in particular around the way the code …
=> Refactor tests

composer.json, tests/ConstantsTest.php, tests/Fixtures/ThirdPartyAnnotations.php, tests/StaticAnalyserTest.php
Upgrade the test for 3rd party annotation support from the abandoned
zendframework to the successor laminas project.
=> Upgrade from abandoned zendframewok to laminas

src/Context.php, src/Processors/AugmentProperties.php
Typecase to `string` to avoid type errors using `preg_xxx` methods on
the value.
Fixes #790 790
=> Make `context->comment` typesafe in case it is not set

docs/Related-projects.md
As the library is compatible with v2, I've opened a PR against 2.x similar to #794
=> Add related project in v2: OpenAPI-Symfony-Routing

src/Processors/MergeJsonContent.php, src/Processors/MergeXmlContent.php, tests/Processors/MergeJsonContentTest.php, tests/Processors/MergeXmlContentTest.php
Supersedes https://github.com/zircote/swagger-php/pull/786 and https://github.com/zircote/swagger-php/pull/777.
Fixes both the XML and Json processor plus adds tests.
Seeing that there is no progress on the other PRs and I've had this sitting around from when I looked at the issue I figured I might as well make it a proper PR...
I think using the parent context is the right choice as the message tries to display parent details of where the invalid child was found.
=> Fix invalid `_context` reference

Examples/misc/misc.yaml, Examples/using-traits/using-traits-inherit.yaml, src/Analysis.php, src/Processors/AugmentSchemas.php, src/Processors/CleanUnmerged.php, src/Processors/InheritInterfaces.php, src/Processors/InheritProperties.php, src/Processors/InheritTraits.php, src/Processors/MergeIntoComponents.php, tests/Fixtures/InheritProperties/BaseInterface.php, tests/Fixtures/InheritProperties/BaseThatImplements.php, tests/Fixtures/InheritProperties/ExtendsBaseThatImplements.php, tests/Fixtures/InheritProperties/TraitUsedByExtendsBaseThatImplements.php, tests/Processors/InheritPropertiesTest.php, tests/UtilTest.php
Make the `InheritProperties` processor deal with existing `allOf` refs
and properties.
Also fixes an issue with redundant `#ref`s in case of multiple inheritance in interfaces and traits.
=> Preserve existing `allOf` when merging properties

Examples/using-traits/using-traits-inherit.yaml, src/Analysis.php, src/Processors/InheritTraits.php
The endless story...
Like classes, traits `use`ing traits need to have those added to their `allOf` property.
This behaviour got lost in PR #798
=> Allow traits also to inherit traits

src/Analysis.php, src/Processors/InheritInterfaces.php, src/Processors/InheritTraits.php
Only inherit an interface/trait if it actually has a schema associated with it.
=> Limit inheriting interface/trait to existing schemas

src/Annotations/Operation.php, tests/Annotations/OperationTest.php, tests/Annotations/SecuritySchemesTest.php, tests/OpenApiTestCase.php
Force each item in the security list to be of type object rather than array/list.
Fixes #811
=> Ensure operation security data conforms to spec

Examples/example-object/example-object.php, Examples/example-object/example-object.yaml, Examples/misc/misc.yaml, Examples/petstore-3.0/petstore-3.0.yaml, Examples/using-interfaces/ProductController.php, Examples/using-interfaces/using-interfaces-inherit.yaml, Examples/using-interfaces/using-interfaces-merge.yaml, Examples/using-refs/ProductController.php, Examples/using-refs/using-refs.yaml, Examples/using-traits/DeleteEntity.php, Examples/using-traits/ProductController.php, Examples/using-traits/using-traits-inherit.yaml, Examples/using-traits/using-traits-merge.yaml, src/Annotations/AbstractAnnotation.php, src/Processors/MergeJsonContent.php, src/Processors/MergeXmlContent.php, tests/OpenApiTestCase.php, tests/Processors/MergeJsonContentTest.php, tests/Processors/MergeXmlContentTest.php
Minor changes that make the generated spec more OAS3 conformant.Improve conforming to the OAS3 specs.
Using https://github.com/stoplightio/spectral to fix issues with test annotations and code:
```
for ff in `find Examples -name *.yaml`; do spectral lint $ff; done
```
=> Improve OAS3 compatibility

src/Annotations/AbstractAnnotation.php, src/Logger.php, tests/LoggerTest.php
Just some code cleanup on shortening class names in log messages.
=> Simplify logging of class names using `@OA\xxx` style

src/StaticAnalyser.php, src/functions.php
PHP8 related changes to namespace parsing.
https://wiki.php.net/rfc/namespaced_names_as_token
=> Add support for new PHP8 T_NAME_xxx token

src/functions.php
=> Fix PHP8 token values to be compatible with other packages

src/Annotations/AbstractAnnotation.php, src/Annotations/OpenApi.php, src/Processors/InheritProperties.php, src/Processors/MergeIntoComponents.php, src/Processors/MergeIntoOpenApi.php, src/Serializer.php, tests/Annotations/AbstractAnnotationTest.php, tests/Annotations/ValidateRelationsTest.php, tests/OpenApiTestCase.php, tests/SerializerTest.php
Alternative PR to #815 which improves on the actual matching.
Refactor of $_nested processing to allow custom nested annotations to work out-of-the-box.
Part of some more clean up in preparation for a more modular internal setup...
Also fixes an issue someone commented on a while back, however I cannot seem to find it any more :/
=> Map custom nested

src/StaticAnalyser.php, tests/Fixtures/Parser/User.php, tests/StaticAnalyserTest.php
Presumably closes #851 by setting the special import key `__NAMESPACE__` that is considered by the `DocParser` during constant resolution.
The problem specified in #851 is tested for by a modification of `Parser/User.php` fixture, in which a class constant is referenced to provide an example value in `@Schema` class annotation.
=> Fix constant resolution in files with namespaces

src/Annotations/Items.php, tests/AnalyserTest.php, tests/Annotations/ItemsTest.php, tests/OpenApiTestCase.php
Adds validation the the `Items` annotation to check that the parent is of type `"array"`.
Also includes some cleanup of defunct tests and cleanup...
Fixes #846.
=> Validate that @OA\Items parent has type "array"

Examples/misc/misc-api.php, Examples/misc/misc.yaml, src/Annotations/MediaType.php, src/Annotations/Parameter.php
Make `MediaType` and `Parameter` resolve examples the same way as `Components`.
Fixes #869
=> Handle multiple @OA\Examples the same everywhere

Examples/misc/misc-api.php, Examples/misc/misc.yaml, tests/ExamplesTest.php
Turns out the `Examples` annotation requires a `summary` property...
This also re-enables the check for logged warnings/errors in the `ExamplesTest`
=> Fix misc example annotations

src/Annotations/AbstractAnnotation.php
If ref is set to null, then generating documentation will cause an exception: `substr() expects parameter 1 to be string, null given` on line 400
This happens for example in `nelmio/api-doc-bundle` when you ref from annotation defined documentation to one stored in config files.
This change will fix the problem by handling null the same as undefined values.
=> Don't crash when ref is null

composer.json
Adds a composer `scripts` target to run `spectral` over all generated specs files in the `Examples` folder
=> Document validation of generated Example specs

src/StaticAnalyser.php, tests/Fixtures/StaticAnalyser/Label.php, tests/Fixtures/StaticAnalyser/Php8AttrMix.php, tests/Fixtures/StaticAnalyser/php7.php, tests/Fixtures/StaticAnalyser/routes.php, tests/StaticAnalyserTest.php
Fix the issue of PHP8 attributes located between docblock and the referenced property/method/class causing the token parser to drop the docblock.
Fixes #906
=> Ignore PHP8 attributes

src/Annotations/AbstractAnnotation.php
If something with illegal utf8 characters are mixed in your swagger doc. Then the swagger.json or swagger.yaml generated by openapi script will  be empty file. In order to fix this problem, the following changes have been made:
1. Remove emoji; 
2. Use JSON_INVALID_UTF8_IGNORE option to call json_encode function.
=> Ignore invalid utf8 characters

src/Context.php
There is type error on PHP 7.2.32:
> Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in /home/webmaster/data/www/vendor/zircote/swagger-php/src/Context.php:212 Stack trace: #0 /home/webmaster/data/www/vendor/zircote/swagger-php/src/Context.php(212): trim(false) #1 /home/webmaster/data/www/vendor/zircote/swagger-php/src/Processors/AugmentOperations.php(26): OpenApi\Context->phpdocDescription() #2 /home/webmaster/data/www/vendor/zircote/swagger-php/src/Analysis.php(466): OpenApi\Processors\AugmentOperations->__invoke(Object(OpenApi\Analysis)) #3 /home/webmaster/data/www/vendor/zircote/swagger-php/src/functions.php(57): OpenApi\Analysis->process(Array) #4 /home/webmaster/data/www/stolplit.ru/mobile_api/generate_doc.php(27): …
=> Fix TypeError when substr return FALSE

Examples/using-traits/Decoration/UndocumentedBell.php, Examples/using-traits/SimpleProduct.php, src/Processors/ExpandTraits.php, src/Processors/MergeTraits.php
Release v3.2.0 breaks traits without class-level phpDocs. A workaround is to set an empty phpDoc with just a description. This was not an issue with v3.1.0.
Context::annotations is null in cases where class-level phpDocs don't exist. This causes foreach() to throw a warning which in certain environments causes a full crash.
=> Regression: Fix traits without class-level phpDocs

src/Analysis.php, src/Context.php, src/Generator.php, src/StaticAnalyser.php, tests/AnalysisTest.php, tests/OpenApiTestCase.php, tests/Processors/BuildPathsTest.php, tests/Processors/CleanUnmergedTest.php, tests/Processors/MergeIntoComponentsTest.php, tests/Processors/MergeIntoOpenApiTest.php, tests/Processors/MergeJsonContentTest.php, tests/Processors/MergeXmlContentTest.php, tests/RefTest.php
Continuing the quest to elimitate static things.
In the long run this will allow to pass around other things in the context, inherited from the `Generator`.
Examples could be processing flags, the target OpenAPI version and other things.
=> Deprecate Context::detect

Examples/processors/schema-query-parameter/scan.php, Examples/processors/schema-query-parameter/schema-query-parameter.json, bin/openapi, src/Analysis.php, src/Generator.php, tests/CommandlineInterfaceTest.php, tests/GeneratorTest.php
* adds non static methods for adding/removing processors.
* deprecates `Analysis::processors()`, `Analysis::registerProcessor()` and `Analysis::unregisterProcessor()`
* also includes a fix for the `schema-query-parameter` processor sample code
=> Add more processor related methods to Generator

src/Analyser.php
The context on the doctrine side is of type `string` and only used in case of exceptions
thrown in the parser.
=> Do not pass the swagger context into doctrines annotation parser

src/Analysis.php
When I updated lib to version 3.3.0 I saw error like this
```
{"message":"OpenApi\\Analysis::addAnnotations(): Argument #2 ($context) must be of type OpenApi\\Context, null given, called in \/app\/vendor\/zircote\/swagger-php\/src\/Analysis.php on line 82"}
```
It happened when you use this lib with [nelmio/api-doc-bundle](https://github.com/nelmio/NelmioApiDocBundle) for symfony
because they use empty constructor
```
$analysis = new Analysis();
$analysis->addAnnotation($this->openApi, null);
```
so I added nullable support and everything works fine  
resolves #997
=> Fix arguments exception, resolves #997

src/Processors/AugmentProperties.php, tests/Fixtures/Customer.php, tests/Processors/AugmentPropertiesTest.php, tests/Processors/AugmentSchemasTest.php
i noticed that we had some fields in our openapi doc that had no type. with some digging, i realized that it was the case for all things that are a typed array that is also nullable. for example `Customer[]|null`.
as a workaround, it works correctly when flipping the order to `null|Customer[]`. but that seems unexpected.
i added a test to prove the problem, and a proposal how to fix it.
=> handle nullable typed arrays

src/Analysers/TokenAnalyser.php, src/Analysers/TokenScanner.php, tests/Analysers/TokenAnalyserTest.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/Php8NamedArguments.php, tests/Fixtures/PHP/php7.php
In particular handle argument names matching reserved words like 'class',
'interface' or 'trait'!
=> Fix token scanning/parsing for PHP8 named arguments

Examples/Readme.md, Examples/polymorphism/AbstractResponsible.php, Examples/polymorphism/Controller.php, Examples/polymorphism/Employee.php, Examples/polymorphism/Fl.php, Examples/polymorphism/Request.php, Examples/polymorphism/polymorphism.yaml, src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Annotations/Flow.php, src/Annotations/OpenApi.php, src/Processors/AugmentProperties.php, src/Processors/AugmentSchemas.php, src/Processors/BuildPaths.php, src/Processors/MergeJsonContent.php, src/Processors/MergeTrait.php, src/Processors/MergeXmlContent.php, tests/UtilTest.php
Flag annotations created by processors as `_aux`. Also pick schema from the end of a context's annotation list as the root annotation should be last (excluding annotations created during processing).
Fixes #1027
=> Reliably pick root schema in Analysis::getSchemaForSource()

Examples/example-object/example-object.yaml, Examples/misc/misc.yaml, Examples/nesting/nesting.yaml, Examples/openapi-spec-attributes/openapi-spec-attributes.yaml, Examples/openapi-spec/openapi-spec.yaml, Examples/petstore-3.0/petstore-3.0.yaml, Examples/petstore.swagger.io/petstore.swagger.io.yaml, Examples/processors/schema-query-parameter/schema-query-parameter.yaml, Examples/swagger-spec/petstore-simple/petstore-simple-3.1.0.yaml, Examples/swagger-spec/petstore-with-external-docs/petstore-with-external-docs.yaml, Examples/swagger-spec/petstore/petstore.yaml, Examples/using-interfaces/using-interfaces.yaml, Examples/using-refs/using-refs.yaml, Examples/using-traits/using-traits.yaml, README.md, bin/openapi, composer.json, docs/Getting-started.md, src/Annotations/AbstractAnnotation.php, src/Annotations/License.php, src/Annotations/OpenApi.php, src/Context.php, src/Generator.php, tests/Analysers/ReflectionAnalyserTest.php, tests/Annotations/LicenseTest.php, tests/Annotations/OpenApiTest.php, tests/ExamplesTest.php, tests/OpenApiTestCase.php
Allows to toggle the openapi version with only '3.1.0' and '3.0.0' being allowed.
Right now this will not affect the generated spec, but that could be added later if required without affecting the `Generator`
=> Allow to set the OpenAPI version

Examples/misc/misc-api.php, Examples/misc/misc.yaml, src/Annotations/License.php, src/Annotations/Response.php
=> Make Response::description optional when $ref is set

src/Attributes/Response.php
This fixes the bug where the `ref` attribute is never set on the `Response` object.
=> `Response`: Pass ref to parent constructor.

src/Attributes/OperationTrait.php
Tags should be an array of strings, not Tag's. This would be a bc-break and it also breaks the openapi generation
=> Change typehint of Operation tags to string

src/Attributes/OperationTrait.php
We just updated versions of PhpStan, and the latest version is spitting this error back at us repeatedly: 
```
Parameter $security of attribute class OpenApi\Attributes\Get constructor expects array<string>|null, array<string, array> given.
```
Basically, the parameter I'm passing is:
```
security: [
[
'ApiKey': []
]
]
```
...which is correct as per the spec, but the hinting in the docblock is expecting an array of strings, when it's really a multidimensional array.
I think this should resolve that issue from the static typing side.
=> Update type-hinting on security property for operations.

src/Attributes/Discriminator.php
In OpenApi\Annotations\Discriminator $mapping typehint string[]
=> Fix Discriminator Attribute mapping property type hint

src/Attributes/ParameterTrait.php
I need to set a `style: deepObject` and `expose` for the query parameter. I found no other way out than to add these two parameters to the attribute constructor.
=> Add Style and Explode to Parameter attribute constuctor

src/Attributes/Examples.php
I had to include "$example" argument to OpenApi\Attributes\Examples constructor, because the library was complaining it was missing. Here's an example where it complained:
```php
#[OA\Get(
path: '/api/v1/activation-codes/{id}/modules',
summary: 'Gets activation code modules',
operationId: 'listmodules',
tags: ['Activation Codes'],
parameters: [new OA\Parameter(ref: '#/components/parameters/ActivationCodeIdRequiredInPath')],
responses: [
new OA\Response(
response: 200,
description: 'Successful operation.',
content: new OA\JsonContent(
ref: '#/components/schemas/ModuleListResponse',
examples: [new OA\Examples(
summary: '2 activation code modules found',
value: ''
)]
)
),
new OA\Response(response: 204, ref: '#/components/responses/SuccessfulEmptyList'),
]
)]
public function …
```
=> Includes 'example' argument in Examples attribute constructor (PHP 8.1)

src/Attributes/Examples.php
Simply support array instead of just strings in `$value` param in Examples attribute constructor:
```php
public function __construct(
?string $summary = null,
?string $description = null,
string|array|null $value = null,
?string $externalValue = null,
string|object|null $ref = null,
// annotation
?array $x = null,
?array $attachables = null
) {
parent::__construct([
'summary' => $summary ?? Generator::UNDEFINED,
'description' => $description ?? Generator::UNDEFINED,
'value' => $value ?? Generator::UNDEFINED,
'externalValue' => $externalValue ?? Generator::UNDEFINED,
'ref' => $ref ?? Generator::UNDEFINED,
'x' => $x ?? Generator::UNDEFINED,
]);
if ($attachables) {
$this->merge($attachables);
}
}
```
=> Support array in Examples value (PHP 8.1)

src/Attributes/Examples.php
This is a suggestion. Is there a reason why Examples attribute can only be attributed to classes? In this PR I enabled the targets methods and properties, just like the OpenApi\Attributes\Schema attribute.
=> Enables more attribute targets for OpenApi\Attributes\Examples.

README.md
I'm not convinced we still promote Annotations over Attributes but dead link is not an answer.
=> Fix a doc link to Annotation support

bin/openapi, src/Loggers/ConsoleLogger.php
This allows to run `bin/openapi` on code that emits errors of type E_DEPRECATED.
Deprecated code should not result in a failing tool, see https://wouterj.nl/2021/11/deprecations-are-not-errors
=> Only exit with code > 0 if the logged message was above notice

src/Attributes/OperationTrait.php
While migrating my code base from Docblock annotations to Attributes I noticed that `deprecated` was missing from the list os supported parameters on OperationalTrait
See also: https://github.com/zircote/swagger-php/issues/1023#issuecomment-1034146418
=> Added deprecated to OperationTrait

docs/reference/annotations.md, docs/reference/attributes.md, docs/refgen.php, src/Annotations/Components.php, src/Annotations/Examples.php, src/Annotations/Flow.php, src/Annotations/Header.php, src/Annotations/MediaType.php, src/Annotations/Operation.php, src/Annotations/Parameter.php, src/Annotations/Response.php, src/Annotations/Schema.php, src/Annotations/SecurityScheme.php
Expects markdown and will add all `@see` refs at the end of property definition.
Also adds some more spacing.
=> Add @see support to annotation property docblocks

src/Attributes/OperationTrait.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
"callbacks" parameter is missing on OperationTrait constructor.
I implemented this bugfix based on PR https://github.com/zircote/swagger-php/pull/1191.
=> Add callbacks parameter to OperationTrait

Examples/polymorphism/Employee.php, Examples/polymorphism/polymorphism-3.1.0.yaml, Examples/polymorphism/polymorphism.yaml, composer.json, docs/guide/cookbook.md, docs/guide/faq.md, docs/guide/migrating-to-v4.md, src/Analysers/ReflectionAnalyser.php, src/Annotations/AbstractAnnotation.php, src/Annotations/Flow.php, src/Annotations/Schema.php, src/Attributes/Property.php, src/Attributes/Schema.php, src/Processors/AugmentProperties.php, tests/ExamplesTest.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
Thanks to @cdaguerre for the idea and initial work; replaces #1147.
- adds support to annotate class constants, see example below 
related to https://github.com/zircote/swagger-php/issues/1082)
- adds support for the `const` keyword to attributes
- handles converting a `const` to a single value `enum` for OAS 3.0.0
```php
use OpenApi\Attributes as OA;
#[OA\Schema()]
class Airport
{
#[OA\Property(property='kind')]
public const KIND = 'Airport';
}
```
```php
use OpenApi\Attributes as OA;
#[OA\Schema()]
class Airport
{
#[OA\Property(
property: 'kind',
type: 'string',
const: 'Airport'
)]
public string $kind = 'Airport';
}
```
This ^^code is equivalent to the example above in terms of generated documentation.
The `const` keyword was introduced in OAS 3.1, eg.
```yaml
components:
schemas: …
```
=> Allow to annotate class constants as properties

Examples/using-interfaces/Product.php, Examples/using-interfaces/using-interfaces.yaml, src/Processors/ExpandInterfaces.php, tests/UtilTest.php
=> Skip inherited interfaces when expanding

src/Analysers/ReflectionAnalyser.php
Initialise optional context properties with `null` rather than `Generator::UNDEFINED`
=> Initialise optional context properties with `null`

docs/guide/migrating-to-v4.md
This guide was very helpful in a recent upgrade I just completed!
I noticed a typo for the word `convenience`. I made a few other minor edits here, as well.
=> Minor documentation fixes for v4 migration guide

src/Generator.php, src/Processors/ExpandClasses.php, src/Processors/ExpandInterfaces.php, tests/GeneratorTest.php
Allows to configure processors (and the `Generator` itself).
To kick things of the only option is to toggle the `OperationId` processor `hash` flag.
Default config:
```php
[
'operationId' => [
'hash' => false
]
]
```
Top level key must match the processor class name (with a lower case'd first char).
Settings are applied via `setXXX()` methods, so unless there is a matching method for the config option nothing will happen.
A minor BC break is that the config is applied each time `Generator::getProcessors()` is called. This allows to also configure custom processors the same way. 
For obvious reasons, `callable` processors are skipped :)
The actual BC break is that swappng the `OperationId` processor for an instance with different configuration wil no longer have any effect.
On the plus …
=> Add support for generator  / processor configuration

src/Annotations/AbstractAnnotation.php, src/Processors/AugmentProperties.php, src/Processors/DocBlockDescriptions.php, src/Processors/DocblockTrait.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml, tests/Processors/ExpandClassesTest.php
Fixes #1226
This changes the way the code determines what is the root annotation in a context. The proposed new way is that an annotation is the root if:
* it is the only annotation
* it is the best match of being an instance **or** subclass of one of these classes (in priority order)
* `OA\Operation`
* `OA\Property`
* `OA\Parameter`
or (lowest priority) of type `OpenApi\Annotations\Schema`or `OpenApi\Attributes\Schema`. In this case the exact class is required.
=> Refactor strategy determining the root annotation in a context

docs/guide/faq.md
Fixes #1161 in that it documents the fact that the console logger uses `error_log` for all output.
=> Add faq about openapi CLI output missing

docs/reference/annotations.md, docs/reference/attributes.md, src/Annotations/Schema.php, src/Annotations/ServerVariable.php, src/Attributes/AdditionalProperties.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/Property.php, src/Attributes/Schema.php, src/Attributes/ServerVariable.php, src/Attributes/XmlContent.php
At the moment you can only use strings in enum, if you use integer or floats, static code analyzers such as Psalm will trigger an error.
E.g. 
When defining an enum of integer values like the one below:
`#[OA\Property(enum: [123, 456, 789], default: 123)]`
Psalm will trigger an InvalidScalarArgument  (https://psalm.dev/docs/running_psalm/issues/InvalidScalarArgument/)
`Argument 1 of OpenApi\Attributes\Property::__construct expects array<array-key, string>|null, array{123, 456, 789} provided`
Thanks @tm1000 for pointing in this direction
=> Change enum type from string[] to string[]|int[]|float[]

src/Processors/ExpandEnums.php, tests/Fixtures/PHP/StatusEnumIntegerBacked.php, tests/Processors/ExpandEnumsTest.php
A `Backed Enum` may be backed by types of int or string
But when I want to use integer in Enum, I saw like this:
-----
These changes can make enum use name or value specifiable.
=> Allow original backing value in Enum

src/Annotations/AbstractAnnotation.php, src/Annotations/Operation.php
Stops the annoying symfony deprecation warnings that the return type is missing
=> fix return type for Symfony debug class

src/Analysers/DocBlockParser.php
Added $context param to DocParser->parse to keep context in exception.
According to:
- https://github.com/doctrine/annotations/blob/1.7/lib/Doctrine/Common/Annotations/DocParser.php#L440
- https://github.com/doctrine/annotations/blob/1.7/lib/Doctrine/Common/Annotations/DocParser.php#L342
Full path of misstype:
> [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'description' in \App\Http\Controllers\Api\V1\SmsSenderNamesController->getSenderNames() in /var/www/API_public/laravel-app/app/Http/Controllers/Api/V1/SmsSenderNamesController.php on line 18:12
much better then:
> [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'description' at position 132.
=> Wrong DocParser Exception without context

src/Context.php, src/Processors/AugmentProperties.php
This is to fix the deprecations with php 8.1
```
php.INFO: Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated at /vendor/zircote/swagger-php/src/Processors/AugmentProperties.php:61)"} []
```
```
php.INFO: Deprecated: preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated at /vendor/zircote/swagger-php/src/Context.php:212)"} []
```
=> type deprecation fix for preg_match and preg_split for php 8.1

tests/Fixtures/PHP/AnonymousFunctions.php
PHP 8.2 deprecates `"${var}"` string interpolation pattern.
This fixes all two of such occurrences in `zircote/swagger-php` package.
- [PHP 8.2: `${var}` string interpolation deprecated](https://php.watch/versions/8.2/${var}-string-interpolation-deprecated)
- [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)
=> [PHP 8.2] Fix `${var}` string interpolation deprecation

src/Analysers/AttributeAnnotationFactory.php
I was looking for a solution to fix https://github.com/nelmio/NelmioApiDocBundle/issues/1993 (explanation of root issue in https://github.com/zircote/swagger-php/issues/1220#issuecomment-1116895871), and I couldn't find an easy one from NelmioApiDocBundle without duplicating a lot of code and making things more likely to break later.
I believe the best solution would be to not return annotations that are already merged in `AttributeAnnotationFactory` so that these may not be merged again later.
This should have no repercussion on zircote/swagger-php internals as attributes returned by `AttributeAnnotationFactory` are passed to `Analysis::addAnnotations` which visits recursively passed annotations and so is able to find merged attributes from their newly defined parents.
What do you think? …
=> Do not return annotations merged into an explicit parent in AttributeAnnotationFactory

src/Processors/Concerns/DocblockTrait.php
Adds `Response` to the list of annotations that can be root annotations and therefore qualify to have the phpdoc comment/summary merged in.
Fixes #1280
=> Add response to the `isRoot` priority map

docs/reference/attributes.md, src/Annotations/RequestBody.php, src/Annotations/Response.php, src/Attributes/RequestBody.php, src/Attributes/Response.php
Relates to https://github.com/nelmio/NelmioApiDocBundle/issues/2023
=> Add Attachable to Response::$content and RequestBody::$content

.gitignore, README.md, docs/reference/annotations.md, docs/reference/attributes.md, src/Annotations/Schema.php, src/Annotations/ServerVariable.php, src/Attributes/AdditionalProperties.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/Property.php, src/Attributes/Schema.php, src/Attributes/ServerVariable.php, src/Attributes/XmlContent.php, src/Processors/ExpandEnums.php, tests/Fixtures/PHP/ReferencesEnum.php, tests/Processors/ExpandEnumsTest.php
I had the need to show just a subset of an enum
It showed correctly in swaggerui, but phpstan and psalm were throwing errors because I couldn't use a \BackedEnum (in my case) to pass to the $enum property
But when I tried to test it, it didnt have the expected result, so I changed the code a bit to be able to parse enums/strings/etc in an array
I used this commit as a starting place https://github.com/zircote/swagger-php/commit/48a769243b4024f3611ab9e8b137a9720d19a3bb
=> Allow enums to be specified with an enum array

bin/openapi
The '-b' option now allows multiple values and also supports `globs`.
=> Allow to specify multiple bootstrap files

src/Analysers/ReflectionAnalyser.php
Fixes an edge case of handling class/trait/interface names in the global namespace where names end up with double leading '\'.
Fixes #1324
=> Fix double '\' when handling classes in the global namespace

Examples/polymorphism/polymorphism-3.1.0.yaml, Examples/polymorphism/polymorphism.yaml, Examples/using-interfaces/using-interfaces.yaml, Examples/using-traits/using-traits.yaml, src/Processors/AugmentSchemas.php, src/Processors/Concerns/MergePropertiesTrait.php, src/Processors/ExpandClasses.php, src/Processors/ExpandInterfaces.php, src/Processors/ExpandTraits.php, tests/Fixtures/Apis/basic.yaml, tests/Fixtures/Scratch/MergeTraits.php, tests/Fixtures/Scratch/MergeTraits.yaml, tests/Fixtures/Scratch/MergeTraitsExtended.php, tests/Fixtures/Scratch/MergeTraitsExtended.yaml, tests/Processors/ExpandClassesTest.php, tests/Processors/ExpandEnumsTest.php, tests/ScratchTest.php, tests/UtilTest.php
=> Extend ExpandClasses processor to also consider ancestor traits

src/Annotations/Parameter.php, src/Attributes/ParameterTrait.php, tests/Annotations/AttributesSyncTest.php, tests/Fixtures/Scratch/ParameterContent.php, tests/Fixtures/Scratch/ParameterContent.yaml, tests/ScratchTest.php
=> Add support for `content` to `Parameter` attribute

composer.json, src/Generator.php, tests/Analysers/DocBlockParserTest.php
=> Allow and support doctrine/annotations ^2.0

src/Processors/AugmentSchemas.php, tests/Fixtures/Scratch/NestedSchema.php, tests/Fixtures/Scratch/NestedSchema.yaml
=> Set `schema` property only on actual `Schema` instances

src/Attributes/Examples.php
=> Allow `Examples` attribute to be repeatable

src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/Php8NamedArguments.php, tests/Fixtures/PHP/php8.php
Reserved keywords such as `class` are legit for named arguments.
Without this fix I get the following error:
```
Message: Uninitialized string offset 1
Class: ErrorException
Code: E_WARNING
File: ./vendor/zircote/swagger-php/src/Analysers/TokenScanner.php:119
```
=> TokenScanner: fix handling of named arguments with reserved keywords

src/Annotations/AbstractAnnotation.php, tests/Fixtures/Scratch/NullRef.yaml, tests/Fixtures/Scratch/NullRef31.yaml
Fixes https://github.com/zircote/swagger-php/issues/1338
It creates a oneOf with a single ref, and with nullable true
=> Allow a ref to be nullable

src/Analysis.php, tests/Fixtures/Scratch/AttributeInheritance.php, tests/Fixtures/Scratch/AttributeInheritance.yaml
=> Use `AbstractAnnotation::isRoot()` as strict check in `Analysis::getAnnotationsOfType()`

src/Analysers/AttributeAnnotationFactory.php, src/Annotations/AbstractAnnotation.php, src/Processors/ExpandClasses.php, src/Processors/ExpandEnums.php, src/Processors/ExpandInterfaces.php, src/Processors/ExpandTraits.php, src/Processors/MergeIntoComponents.php, src/Processors/MergeIntoOpenApi.php, tests/Analysers/ReflectionAnalyserTest.php, tests/Annotations/AbstractAnnotationTest.php, tests/Fixtures/Scratch/ComplexCustomAttributes.php, tests/Fixtures/Scratch/ComplexCustomAttributes.yaml, tests/Processors/ExpandEnumsTest.php
Simplify and cleanup annotation type comparison based on the `OpenApi\\Annotations\\` root annotation.
All rules and logic around nesting are based on annotation class names in the `OpenApi\\Annotations\\` namespace which means attribute and other derived annotation classes need to be reduced to their root annotations in order to evaluate those rules.
Fixes the main aspect of #1416
=> Refactor annotation root comparisons

src/Analysers/AttributeAnnotationFactory.php, tests/Analysers/AttributeAnnotationFactoryTest.php, tests/Fixtures/InvalidPropertyAttribute.php
The error catching in the `AttributeAnnotationFactory` made it hard to find the reason for "ignored" attributes. This change addresses the issues #1267 and #1162.
Instead of catching errors of non existing attribute classes, the existence of the class is checked before the attribute is tried to instantiate. This reveals invalid attribute definitions, but still errors for unknown attributes won't be shown.
=> Removed error catching on invalid attributes

docs/reference/annotations.md, docs/reference/attributes.md, src/Annotations/CookieParameter.php, src/Annotations/Examples.php, src/Annotations/Header.php, src/Annotations/HeaderParameter.php, src/Annotations/JsonContent.php, src/Annotations/Parameter.php, src/Annotations/PathParameter.php, src/Annotations/QueryParameter.php, src/Annotations/RequestBody.php, src/Annotations/Response.php, src/Annotations/Schema.php, src/Annotations/SecurityScheme.php
I added documentation to annotations with No details available and improved a few others.
=> Better documentation for annotations/attributes

src/Processors/ExpandEnums.php, tests/Fixtures/PHP/Enums/TypeEnumStringBacked.php, tests/Fixtures/PHP/ReferencesEnum.php, tests/Processors/ExpandEnumsTest.php
The expression:
```php
new OA\Items(description: 'Event name', type: 'string', enum: [
EnumFoo::class,
EnumBar::class,
'random-string',
])
```
will be parsed into:
```yml
items:
description: 'Event name'
type: string
enum:
- EnumFooCase1
- EnumFooCase2
- EnumFooCase3
- EnumBarCase1
- EnumBarCase2
- random-string
```
=> Support Multiple Enums class-names in Schema::enum property

src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/MultipleFunctions.php
The following expression:
```php
isset($category->{'name'.$prefix}) && $category->{'name'.$prefix} ? $category->{'name'.$prefix} : $category->name;
```
will result in an error if the code contains an opening curly brace followed by a closing curly brace and a colon first. In this case, it won't recognize the closing curly brace correctly and will fail to generate all subsequent endpoints.
=> Fix skip closing curly brace

src/Annotations/AbstractAnnotation.php, src/Annotations/Get.php, src/Context.php, tests/AbstractAnnotationTest.php
This PR fixes two deprecated errors in PHP 8.1/8.2.
* `PHP Deprecated:  Creation of dynamic property Swagger\Context::{$prop} is deprecated in swagger-php/src/Context.php on line 53`
* `Deprecated: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in swagger-php/src/Context.php on line 288`
No more errors when doing `composer test` in PHP 8.1/8.2.
Fixes #1455
=> Fix deprecated error in PHP 8.1/8.2  

src/Processors/AugmentRefs.php, tests/Fixtures/Scratch/DuplicateRef.php, tests/Fixtures/Scratch/DuplicateRef.yaml, tests/Processors/ExpandClassesTest.php
=> Remove duplicate `$ref` in `allOf`

src/Processors/ExpandEnums.php
=> Avoid unguarded use of `enum_exists`

src/Annotations/AbstractAnnotation.php, tests/Fixtures/Scratch/NullRef.yaml, tests/Fixtures/Scratch/NullRef31.yaml
=> Preserve properties when `$ref` is nullable

Examples/nesting/nesting.yaml, Examples/polymorphism/polymorphism-3.1.0.yaml, Examples/polymorphism/polymorphism.yaml, Examples/using-interfaces/using-interfaces.yaml, Examples/using-refs/using-refs.yaml, Examples/using-traits/using-traits.yaml, src/Processors/AugmentSchemas.php, tests/Fixtures/Apis/basic.yaml, tests/Fixtures/Scratch/AttributeInheritance.yaml, tests/Fixtures/Scratch/Docblocks.yaml, tests/Fixtures/Scratch/MergeTraitsExtended.yaml
=> Set `type: 'object'` when moving properties into `allOf`

docs/reference/attributes.md, src/Attributes/AdditionalProperties.php, tests/Fixtures/Scratch/NestedAdditionalProperties.php, tests/Fixtures/Scratch/NestedAdditionalProperties.yaml
Since nested AdditionalProperties have been allowed for a while through #706 also allow it through Attributes and not only with annotations.
=> Allow recursive nesting of AdditionalProperties in Attributes

docs/reference/annotations.md, docs/reference/attributes.md, src/Annotations/RequestBody.php, src/Attributes/RequestBody.php
=> Fix RequestBody content type-hint

README.md, composer.json, docs/guide/annotations.md, docs/reference/annotations.md, docs/reference/attributes.md, src/Analysers/AnnotationFactoryInterface.php, src/Analysers/AttributeAnnotationFactory.php, src/Analysers/DocBlockAnnotationFactory.php, src/Analysers/DocBlockParser.php, src/Analysers/ReflectionAnalyser.php, tests/Analysers/ReflectionAnalyserTest.php
=> Make doctrine/annotations optional

docs/reference/processors.md, src/Analysis.php, src/Generator.php, src/Processors/AugmentRefs.php, src/Processors/AugmentRequestBody.php, tests/Fixtures/Request.php, tests/Processors/AugmentRefsTest.php, tests/Processors/AugmentRequestBodyTest.php
Includes https://github.com/zircote/swagger-php/pull/1542
Added resolving components like header, requestBody and so. 
Berole only schemas can be resolved by AugmentRefs
=> feat: Added resolving references of components (not only schemas)

src/Annotations/AbstractAnnotation.php, src/Annotations/RequestBody.php, tests/Fixtures/Scratch/RequestBody.php, tests/Fixtures/Scratch/RequestBody.yaml
=> Fix resolving general component refs

src/Annotations/AbstractAnnotation.php
[NelmioApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle) is currently attempting to upgrade PHPStan to level 6.
Our annotations which extend `AbstractAnnotation` are generating errors. A simple typehint fixes this which is the reason for this PR :)
https://github.com/nelmio/NelmioApiDocBundle/blob/a585e502725d7e3cfcec25f7a3d59443842006da/src/Annotation/Model.php#L30
```
------ -------------------------------------------------------------------------------------------------------------------- 
Line   Annotation/Model.php                                                                                                
------ -------------------------------------------------------------------------------------------------------------------- 
30     Property …
```
=> Update $_required typehint

phpstan-baseline.neon, src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Annotations/License.php, src/Annotations/OpenApi.php, src/Annotations/Schema.php, src/Context.php, src/Generator.php, src/Processors/AugmentProperties.php, tests/Analysers/ReflectionAnalyserTest.php, tests/OpenApiTestCase.php
Fixes #1562 
This PR also (re-)enables the deprecation trigger in `Context:detect()`. The problems the changes around the version check illustrate how fragile the whole concept of `Context` is and not caring about where/what is in the context is asking for trouble.
=> [4.9] Default openapi version in `Context` to 3.0.0

Examples/Readme.md, Examples/processors/schema-query-parameter-attributes/SchemaQueryParameter.php, Examples/processors/schema-query-parameter-attributes/app/OpenApi.php, Examples/processors/schema-query-parameter-attributes/app/Product.php, Examples/processors/schema-query-parameter-attributes/app/ProductController.php, Examples/processors/schema-query-parameter-attributes/scan.php, Examples/processors/schema-query-parameter-attributes/schema-query-parameter.yaml, phpstan-baseline.neon
Same as `schema-query-parameter` #783 but with attributes support
=> Add example schema-query-parameter-attributes processor

.php-cs-fixer.dist.php, src/Annotations/AbstractAnnotation.php
When I execute my test with the last version of packages + PHP 8.3, I have warnings like this one : 
> 1x: Method "JsonSerializable::jsonSerialize()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "OpenApi\Annotations\AbstractAnnotation" now to avoid errors or add an explicit @return annotation to suppress this message.
=> Update `jsonSerialize` return

composer.json, phpstan-baseline.neon, src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/namespaces3.php, tests/Fixtures/Scratch/ExclusiveMinMax.php, tests/Fixtures/Scratch/ExclusiveMinMax3.0.0.yaml, tests/Fixtures/Scratch/ExclusiveMinMax3.1.0.yaml, tests/Fixtures/Scratch/NullRef.php, tests/Fixtures/Scratch/ParameterContent.php, tests/Fixtures/Scratch/ThirdPartyAnnotation.php, tests/Fixtures/Scratch/ThirdPartyAnnotation3.0.0.yaml, tests/Fixtures/Scratch/ThirdPartyAnnotation3.1.0.yaml
=> Re-implement `TokenScanner` using nikic/php-parser

src/Analysers/AttributeAnnotationFactory.php, src/Analysers/DocBlockAnnotationFactory.php, src/Analysers/DocBlockParser.php, src/Context.php
=> Collect unrelated annotations/attributes in `Context::other`

src/Generator.php
fixes #1603 
The options `processors` was nullable before, now this throws an error, because the parameters of the generator setter are not nullable. Also, the set method for `setProcessorPipline` was executed twice, which makes the first call redundant. 
Now not provided options for `processor` and `processors` should work, with `processor` having priority over `processors`.
=> Fix nullable processor call

Examples/swagger-spec/petstore/petstore.yaml, Examples/using-links-php81/using-links-php81.yaml, Examples/using-refs/using-refs.yaml, Examples/using-traits/using-traits.yaml, src/Generator.php, src/Processors/AugmentTags.php, tests/Fixtures/Scratch/ComplexCustomAttributes3.0.0.yaml, tests/Fixtures/Scratch/ComplexCustomAttributes3.1.0.yaml, tests/Fixtures/Scratch/ParameterContent3.0.0.yaml, tests/Fixtures/Scratch/ParameterContent3.1.0.yaml, tests/Fixtures/Scratch/Tags.php, tests/Fixtures/Scratch/Tags3.0.0.yaml, tests/Fixtures/Scratch/Tags3.1.0.yaml
Automatically adds missing tags to the `OpenApi` spec.
Fixes #1610
=> Add `AugmentTags` processor

docs/reference/processors.md, src/Processors/AugmentParameters.php, src/Processors/CleanUnusedComponents.php, src/Processors/OperationId.php, src/Processors/PathFilter.php, tools/procgen.php, tools/refgen.php, tools/src/Docs/DocGenerator.php, tools/src/Docs/ProcGenerator.php
=> Improve processor reference

src/Analysers/AttributeAnnotationFactory.php, tests/Analysers/ReflectionAnalyserTest.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/Php8PromotedProperties.php
A reproduction of the bug described in my comment here:  https://github.com/zircote/swagger-php/issues/1419#issuecomment-2200163118
Added regression test + fixed it with a clone of context. Tests passing. However - suggestions for alternative fixes are very welcome.
=> Fix promoted properties sharing context

src/Processors/AugmentTags.php, tests/Fixtures/Scratch/Tags.php, tests/Fixtures/Scratch/Tags3.0.0.yaml, tests/Fixtures/Scratch/Tags3.1.0.yaml
=> Remove unused tags

src/Generator.php, tests/Fixtures/SurplusTag.php, tests/OpenApiTestCase.php, tests/Processors/AugmentTagsTest.php, tests/Processors/CleanUnusedComponentsTest.php
Cleanup of tags can only happen after `CleanUnusedComponents` has run
=> Move `AugmentTags` after `CleanUnusedComponents`

src/Processors/AugmentTags.php, tests/Fixtures/UnusedTags.php, tests/Processors/AugmentTagsTest.php
The changes in https://github.com/zircote/swagger-php/pull/1625 mean that we cannot have descriptive tags that do not have a reference to them from an operation. It is nice to allow this so we can have pages dedicated to be informative only (and allow external links directly to that section in the page).
eg. tags like
* introduction
* setup
* how-to
=> allow unused tags to be kept

docs/reference/attributes.md, docs/reference/processors.md, src/Processors/AugmentTags.php
=> Fix processor option default

src/Generator.php, tests/GeneratorTest.php
=> Fix handling of `processor` option in `Generator::scan()`

src/Analysers/AttributeAnnotationFactory.php
This change somewhat loosens the restrictions about nesting of custom `Attachable` annotations to allow proper nesting of custom annotations.
TO avoid bad nesting it is strongly recommended to limit parent/child relationships by implementing the `Attachable::allowedParents()` method. (This will be enforced in v5).
=> Allow nesting of `Attachable` annotations

docs/reference/annotations.md, docs/reference/attributes.md, src/Annotations/Components.php, src/Annotations/Contact.php, src/Annotations/Discriminator.php, src/Annotations/Examples.php, src/Annotations/ExternalDocumentation.php, src/Annotations/Flow.php, src/Annotations/Header.php, src/Annotations/Info.php, src/Annotations/License.php, src/Annotations/Link.php, src/Annotations/MediaType.php, src/Annotations/OpenApi.php, src/Annotations/Operation.php, src/Annotations/Parameter.php, src/Annotations/PathItem.php, src/Annotations/RequestBody.php, src/Annotations/Response.php, src/Annotations/Schema.php, src/Annotations/SecurityScheme.php, src/Annotations/Server.php, src/Annotations/ServerVariable.php, src/Annotations/Tag.php, src/Annotations/Xml.php, src/Serializer.php, tools/src/Docs/RefGenerator.php
=> Update external links to OpenAPI spec

src/Annotations/Response.php
If a `description` or `ref` is missing in `Response` annotation, this improves the warning message, telling where exactly the missing attribute for the annotation is, saving up one's debugging time.
=> Expand on Response annotation warning message.

docs/reference/generator.md
In this generator [document,](https://zircote.github.io/swagger-php/reference/generator.html#the-openapi-generator-class) the example for generator does not work, due to bracket placed incorrectly.
This change is to fix that example.
=> fix: bracket correction in readme

.github/workflows/code-style.yml, .github/workflows/gh-pages.yml, .github/workflows/static-analysis.yml, composer.json, phpstan-baseline.neon, phpstan.neon, psalm-baseline.xml, psalm.xml, src/Analysers/AttributeAnnotationFactory.php, src/Analysers/TokenScanner.php, src/Processors/Concerns/DocblockTrait.php, src/Processors/MergeIntoOpenApi.php, tests/Analysers/DocBlockParserTest.php, tests/Processors/AugmentSchemasTest.php, tests/Processors/MergeJsonContentTest.php, tests/Processors/MergeXmlContentTest.php, tests/SerializerTest.php
Fixes #1690 (in that v5 is allowed once psalm supports it)
=> Update tooling and dependency versions

src/Generator.php
Initialize `Generator::$context` to avoid a `Typed static property OpenApi\Generator::$context must not be accessed before initialization` error when `Generator::$context` is called from the `AbstractAnnotation` constructor (line 101).
Fixes #1693
=> Initialize Generator::$context

src/Annotations/Items.php
=> Consider `type` might be an array when checking `Item` parent type

composer.json, docs/.vitepress/config.js, docs/guide/examples.md, docs/reference/generator.md, examples/specs/api/Readme.md, examples/specs/petstore/Readme.md, tools/examplegen.php, tools/procgen.php, tools/refgen.php, tools/src/Docs/ExampleGenerator.php
Edit: Reducing scope to get things out. Tweaking the actual example files can be done in separate PRs.
=> Integrate api, petstore examples into docs

.meta-storm.xml
Here is MetaStorm integration. Get more about MetaStorm:
- [Source](https://github.com/xepozz/meta-storm-idea-plugin)
- [Marketplace](https://plugins.jetbrains.com/plugin/26121-meta-storm/)
I'm not a big fan of writing open api manually, but sometimes I should do it. Last time I modified the attributes notation I've noticed that there are not suggestions for query/path/header/cookie in "in" parameter, no suggestions about media type.
I've added some to help other users do not a typo. 
One more thing is global collection `GLOBAL:media-types` will be available soon, currently it's absent it released versions.
=> feat: MetaStorm Integration

docs/.vitepress/config.js, docs/.vitepress/theme/custom.css, docs/index.md, docs/package.json
There are some slight differences between the versions. Since there is now an official dark mode I decided to leave the codeblocks in the light style if darkmode isn't enabled. But I can change it if requested.
=> Update vitepress, closes #1720

docs/reference/annotations.md, docs/reference/attributes.md, docs/reference/processors.md, src/Annotations/JsonContent.php, src/Attributes/JsonContent.php, src/Processors/Concerns/DocblockTrait.php, tools/src/Docs/DocGenerator.php
Also properly handle sample code in `src` docblocks when generating docs.
Adds documentation to `JsonContent` on how to use vs. `MediaType`
resolves #1638
=> Preserve docblock indentation

src/Processors/ExpandEnums.php, tests/Processors/ExpandEnumsTest.php
Currently, in the OpenAPI spec, there's no standardized way to persist the name of enums when the value of the enum is stored in the `enum` value. There are competing implementations for providing this data in the form of extensions, but one with widespread support is `x-enumNames`, used by NSwag, `swagger-api-typescript`, and SwaggerUI via a plugin.
This PR specifically expands the enum processing to automatically generate the `x-enumNames` values in cases where the enum name isn't used as the value. This ensures that we're able to use this data in other libraries.
I figured I'd offer it as a PR since it may be of utility to more than just me, but I realize that it's using an extension and I can also implement it via directly modifying the pipeline myself. Either way, perhaps it's …
=> Support `x-enumNames` for `BackedEnum`s

src/Attributes/AdditionalProperties.php, src/Attributes/Components.php, src/Attributes/Contact.php, src/Attributes/Discriminator.php, src/Attributes/Examples.php, src/Attributes/ExternalDocumentation.php, src/Attributes/Flow.php, src/Attributes/Header.php, src/Attributes/Info.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/License.php, src/Attributes/Link.php, src/Attributes/MediaType.php, src/Attributes/OpenApi.php, src/Attributes/OperationTrait.php, src/Attributes/ParameterTrait.php, src/Attributes/PathItem.php, src/Attributes/Property.php, src/Attributes/RequestBody.php, src/Attributes/Response.php, src/Attributes/Schema.php, src/Attributes/SecurityScheme.php, src/Attributes/Server.php, src/Attributes/ServerVariable.php, src/Attributes/Tag.php, src/Attributes/Webhook.php, src/Attributes/Xml.php, src/Attributes/XmlContent.php
Fix duplicate `attachables` and format `attachables` assignment.
Bug display:
https://github.com/zircote/swagger-php/blob/18457fa71f753cfd4a2b21916baf329864fdfaa6/src/Attributes/Schema.php#L110-L111
=> Fix duplicate attachables

bin/openapi, src/Analysers/AnalyserInterface.php, src/Analysers/AnnotationFactoryInterface.php, src/Analysers/AttributeAnnotationFactory.php, src/Analysers/DocBlockAnnotationFactory.php, src/Analysers/ReflectionAnalyser.php, src/GeneratorAwareInterface.php, src/GeneratorAwareTrait.php
Changes namespace of `GeneratorAwareTrait`.
=> Improve `GeneratorAware` trait and interface

src/Analysers/AttributeAnnotationFactory.php, src/Generator.php, tests/Analysers/AttributeAnnotationFactoryTest.php, tests/Fixtures/PHP/Label.php, tests/Fixtures/UsingAttributes.php
Adds an option to `AttributeAnnotationFactory` to ignore non `OpenApi` annotations and not instantiate them.
This can be done by either instantiating the `AttributeAnnotationFactory` yourself or by configuring this in the `Generator`.
```php
(new Generator())
->setConfig([
'generator' => [
'ignoreOtherAttributes' => true,
],
]);
```
Fixes #1747
=> Allow to ignore non `OpenApi` attributes

Changelog.md
This is misleading, as there are migration [guidelines documented](https://github.com/DerManoMann/swagger-php/tree/master/docs/guide).
=> Removes Changelog.md

src/Analysers/AttributeAnnotationFactory.php, tests/Fixtures/Scratch/PromotedProperty.php, tests/Fixtures/Scratch/PromotedProperty3.0.0.yaml, tests/Fixtures/Scratch/PromotedProperty3.1.0.yaml
=> Unexpected property

tests/CommandlineTest.php, tests/ContextTest.php, tests/UtilTest.php
Summary of changes for tests to work in windows environments:
- normalized paths where possible for assertions
- use DIRECTORY_SEPARATOR inside paths where normalization is not possible
- prepend `php` to command line tests
- use `NUL` instead of `/dev/null` for error output in command line tests
=> FIX tests for windows

src/Annotations/OpenApi.php, tests/RefTest.php
```php
@OA\Schema(
schema="String",
@OA\Property(property="value", type="string"),
x={
"custom-key": @OA\Schema(
@OA\Property(property="value", type="string"),
)
}
)
```
The above annotation will generate `x-custom-key` in the OpenAPI document.
However, we need to get ref of `x-custom-key` with `$openapi->ref('#/components/schemas/String/x/custom-key')` (note that here we use `x/custom-key` instead of `x-custom-key`).
This is not conducive to writing ref in the code ourselves. For example,
```php
@OA\Post(
path="/api/~/endpoint",
@OA\Response(
response="default",
description="A response",
@OA\JsonContent(ref="#/components/schemas/String/x/custom-key")
)
)
```
This will generate the following incorrect documentation when using `$openapi->toYaml()`(use `x/custom-key`)
```yaml
... …
```
=> Support use x-* in ref
