zircote/swagger-php

src/Annotations/Parameter.php
Second attempt, f*** up my branch.  Relates to #253, #3236b99
=> Allow free parameter formats

README.md, src/Serializer.php, tests/SerializerTest.php
In this PR: 
- Support deserialize a json string to specific Swagger Annotations object;
- Add tests;
=> add deserializer and test

docs/Getting-started.md
Thank you so much for this documentation! I'm loving swagger-php!
I found these spelling/grammar mistakes in this file so I'm submitting a pull request with fixes.
=> some grammar and spelling fixes

Examples/petstore.swagger.io/models/User.php
Add missed parenthesis in annotations for User#firstName
=> Add missing parenthesis in annotations for User#firstName

src/Annotations/Parameter.php
=> Annotations\Parameter->items - fix PHP docblock

src/Util.php
If I have many classes in different directories, I can create a directory, create files and directories link in it. Add this method, swagger-php will follow this structure as well.
=> enable finder search follow link files and directories

docs/Getting-started.md
=> Example with array as value for custom properties

src/Processors/AugmentProperties.php, tests/AugmentPropertiesTest.php, tests/Fixtures/Customer.php
https://github.com/zircote/swagger-php/pull/345
Base on https://github.com/zircote/swagger-php/pull/345 with tests
=> add test example property

Examples/using-refs/api-spec.php
=> Fixed docs

docs/Getting-started.md
I noticed a few mistypes whilst reading through, so correcting them 🙂
=> Tidy up mistypes in Getting-started.md

src/Processors/AugmentProperties.php, tests/AugmentDefinitionsTest.php, tests/AugmentPropertiesTest.php, tests/Fixtures/Customer.php
=> Add var type detection when null is also set 

docs/Related-projects.md
It would be nice if those changes also get pushed to zircote.com at some point :)
Cheers, mano
=> Add openapi-verifier project

.travis.yml, src/StaticAnalyser.php
=> PHP 7.4 Support

src/Analysis.php, src/Context.php, src/Processors/AugmentSchemas.php, src/Processors/ImportInterfaces.php, src/StaticAnalyser.php, tests/AugmentSchemasTest.php, tests/Fixtures/CustomerInterface.php, tests/UtilTest.php
Fixes #713 
Might be missing more tests?
=> [interface-parsing] parse interfaces, just like classes and traits

Examples/schema-query-parameter-processor/SchemaQueryParameter.php, Examples/schema-query-parameter-processor/app/Product.php, Examples/schema-query-parameter-processor/app/ProductController.php, Examples/schema-query-parameter-processor/app/api-spec.php, Examples/schema-query-parameter-processor/scan.php, Examples/schema-query-parameter-processor/schema-query-parameter-processor.json
Custom processor that injects parameters into operations based on a
vendor extension annotation.
Showcases a solution for #663
=> Add simple example of using a custom processor

Examples/using-traits/using-traits-inherit.yaml, Examples/using-traits/using-traits-merge.yaml, src/Processors/OperationId.php, tests/Fixtures/Processors/EntityControllerClass.php, tests/Fixtures/Processors/EntityControllerInterface.php, tests/Fixtures/Processors/EntityControllerTrait.php, tests/Processors/OperationIdTest.php, tests/UtilTest.php
Add support for FQDN in operationId for interfaces and traits
=> Improve operation id for interfaces and traits

composer.json, src/Analyser.php, src/StaticAnalyser.php
Bump doctrine dependency to 1.7 to make things work in 7.3/7.4 even with the lowest possible dependencies 
(`composer --prefer-lowest`)
=> Bump doctrine deps and cleanup some cruft

composer.json, src/Analyser.php, src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Annotations/Flow.php, src/Annotations/Items.php, src/Annotations/OpenApi.php, src/Annotations/Operation.php, src/Annotations/Parameter.php, src/Annotations/Schema.php, src/Annotations/SecurityScheme.php, src/Context.php, src/Logger.php, src/Processors/DocBlockDescriptions.php, src/Processors/InheritProperties.php, src/Serializer.php, src/StaticAnalyser.php, src/Util.php, tests/ContextTest.php
* add more type hints
* remove redundant phpdoc
* fix some more phpstan/psalm issues
=> Codestyle cleanup

Examples/petstore-3.0/controllers/Store.php, Examples/petstore-3.0/petstore-3.0.yaml
fix error: Semantic error at paths./store/order/{orderId}.get.parameters.0.schema.minimum: 'minimum' must be lower value than 'maximum'
=> Update Store.php: fix minimum error

Examples/example-object/example-object.php, Examples/example-object/example-object.yaml
=> Show how to set multiple examples

docs/Related-projects.md
Swag It PHP converts JSON to (partial) PHP Swagger annotations.
See:  https://github.com/zircote/swagger-php/issues/909
Replaces: https://github.com/zircote/swagger-php/pull/911
=> fix(#909): Add Swag It PHP to Related Projects

Examples/misc/misc-api.php, Examples/misc/misc.yaml
=> Add bearer auth security example

src/functions.php
Related issue https://github.com/zircote/swagger-php/issues/919
=> Fix errors with php < 8

.github/workflows/build.yml, .github/workflows/security-checks.yml
=> Clean up invalid args

README.md, docs/.vuepress/config.js, docs/Supported-annotations.md
Adds a stub documentation site for supported annotations
Kind of closes #905
=> Add documentation site for supported annotations

src/Generator.php
Skip invalid sources and log a warning.
=> Skip invalid sources

Examples/using-refs/ProductController.php, Examples/using-refs/using-refs.yaml, composer.json
Improve validation of generated example specs.
=> Fix response refs

src/Processors/InheritTraits.php, src/Processors/MergeTraits.php, tests/Processors/InheritPropertiesTest.php
Flag `MergeTraits` and `InheritTraits` processors deprecated
=> Flag MergeTraits processor deprecated

composer.json, tests/AnalysisTest.php, tests/Fixtures/AnotherNamespace/Child.php, tests/Fixtures/AnotherNamespace/ChildWithDocBlocks.php, tests/Fixtures/InheritProperties/Ancestor.php, tests/Fixtures/InheritProperties/AncestorWithoutDocBlocks.php, tests/Fixtures/InheritProperties/Base.php, tests/Fixtures/InheritProperties/Extended.php, tests/Fixtures/InheritProperties/ExtendedWithTwoSchemas.php, tests/Fixtures/InheritProperties/ExtendedWithoutAllOf.php, tests/Fixtures/InheritProperties/GrandAncestor.php
* Adds `composer/package-versions-deprecated`
* Fixes some fixture namespaces
=> Add package deprecated checker

src/Annotations/AbstractAnnotation.php, src/Annotations/Operation.php, src/Annotations/SecurityScheme.php
=> fix php 8.1 deprecations in 2.x

.github/workflows/build.yml, .github/workflows/code-style.yml
Also perform the check on PHP 8 instead of PHP 7.4
=> Make the codestyle check a separate action

src/Annotations/Parameter.php
=> Add missing parameter attribute args

src/Annotations/AbstractAnnotation.php, src/Annotations/Examples.php
Includes alternative fix for #1029
=> Minor fixes

Examples/processors/schema-query-parameter/app/ProductController.php, Examples/processors/schema-query-parameter/schema-query-parameter.yaml, Examples/swagger-spec/petstore-simple/api.php, Examples/swagger-spec/petstore-simple/petstore-simple.yaml, Examples/swagger-spec/petstore/api.php, Examples/swagger-spec/petstore/petstore.yaml, src/Annotations/License.php, src/Attributes/License.php, tests/Annotations/LicenseTest.php
Also fixes a couple spectral validation issues
=> OpenApi 3.1.0 updates for `Licence`

src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/Php8NamedProperty.php
=> Detect promoted properties

src/Annotations/RequestBody.php
- Fixed RequestBody annotation docs
=> Fixed RequestBody docs

Examples/nesting/nesting.yaml, Examples/swagger-spec/petstore-simple/petstore-simple-3.1.0.yaml, Examples/swagger-spec/petstore-simple/petstore-simple.yaml, Examples/swagger-spec/petstore-with-external-docs/petstore-with-external-docs.yaml, Examples/using-interfaces/using-interfaces.yaml, Examples/using-refs/using-refs.yaml, Examples/using-traits/using-traits.yaml, src/Generator.php, src/Processors/AugmentRefs.php, src/Processors/AugmentSchemas.php, tests/Fixtures/Apis/basic.yaml, tests/Processors/ExpandClassesTest.php
=> Refactor ref rewriting

src/Processors/AugmentProperties.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
=> Map property type for promoted properties

src/Analysers/AttributeAnnotationFactory.php, src/Analysers/ReflectionAnalyser.php, tests/Analysers/ReflectionAnalyserTest.php, tests/Analysers/TokenAnalyserTest.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/Php8PromotedProperties.php
=> Skip constructor properties only for attributes

src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/Property.php, src/Attributes/Schema.php, src/Attributes/XmlContent.php
=> Fix typehints for additionalProperties

Examples/using-links-php81/MyAttribute.php, Examples/using-links-php81/User.php, src/Analysers/AttributeAnnotationFactory.php, tests/ExamplesTest.php
=> Handle unknown attributes

.github/workflows/gh-pages.yml
Set to trigger on release create.
=> Enable gh-pages workflow

src/Analysers/AttributeAnnotationFactory.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
=> Promoted property attribute type override

src/Attributes/SecurityScheme.php, src/Attributes/Tag.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
=> Allow Tag and SecuritScheme to be repeatable

src/Attributes/Server.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
=> Allow multiple Server attributes

src/Attributes/Schema.php
=> Tweak properties doctype hint

src/Analyser.php
=> Fix deprecated messages

src/Processors/OperationId.php, tests/Processors/OperationIdTest.php
=> Ignore operationId `null`

src/Attributes/Components.php, src/Attributes/OpenApi.php
=> Add missing attribute Components parameter

src/Attributes/RequestBody.php
Fixes issue https://github.com/zircote/swagger-php/issues/1172
=> Add missing `request` parameter for RequestBody.php

src/Attributes/RequestBody.php
Additional fix for issue https://github.com/zircote/swagger-php/issues/1172
=> Add missing `ref` parameter for RequestBody.php

README.md, docs/guide/index.md
=> Document PHP requirements

README.md
=> Fix Generator reference link

src/Attributes/OpenApi.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml
=> Add security parameter to OpenApi attribute

src/Attributes/Parameter.php, src/Attributes/PathParameter.php
=> Sync attribute flags and add `\Attribute::TARGET_PARAMETER`

src/Analysers/DocBlockAnnotationFactory.php, src/Analysers/DocBlockParser.php, tests/Fixtures/UsingCustomAttachables.php
=> Fix injecting docblock parser aliases

src/Annotations/AbstractAnnotation.php, src/Serializer.php, tests/ExamplesTest.php
Also tests the `Serializer` against all example yaml files.
=> Add YAML support to Serializer

docs/reference/annotations.md, docs/reference/attributes.md, docs/refgen.php
Also hide annotation properties for nested elements as those are not used directly.
=> Document parent and nested elements

src/Analysers/AttributeAnnotationFactory.php, src/Attributes/ParameterTrait.php, tests/Fixtures/Apis/Attributes/basic.php, tests/Fixtures/Apis/DocBlocks/basic.php, tests/Fixtures/Apis/Mixed/basic.php, tests/Fixtures/Apis/basic.yaml, tests/OpenApiTestCase.php
Also avoid adding inherited comments to `Schema` nested in `Parameter`
=> Handle `required` for `Parameter`

src/Annotations/Examples.php, src/Annotations/Header.php, src/Annotations/Link.php, src/Annotations/Parameter.php, src/Annotations/PathItem.php, src/Annotations/RequestBody.php, src/Annotations/Response.php, src/Annotations/Schema.php, src/Annotations/SecurityScheme.php, src/Attributes/AdditionalProperties.php, src/Attributes/Examples.php, src/Attributes/Header.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/Link.php, src/Attributes/ParameterTrait.php, src/Attributes/Property.php, src/Attributes/RequestBody.php, src/Attributes/Response.php, src/Attributes/Schema.php, src/Attributes/SecurityScheme.php, src/Attributes/XmlContent.php
=> Re-add object as typehint for `$ref`

src/Attributes/Tag.php
=> Allow Tag attribute on methods

src/Attributes/Property.php
=> Allow the property attribute to be repeated

src/Attributes/SecurityScheme.php
=> Allow SecurityScheme on methods/properties

src/Analysers/AttributeAnnotationFactory.php, tests/Fixtures/Apis/Attributes/basic.php
=> Detect nullable on constructor property promotion

src/Annotations/AbstractAnnotation.php, src/Attributes/AdditionalProperties.php, src/Attributes/Components.php, src/Attributes/Contact.php, src/Attributes/Discriminator.php, src/Attributes/Examples.php, src/Attributes/ExternalDocumentation.php, src/Attributes/Flow.php, src/Attributes/Header.php, src/Attributes/Info.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/License.php, src/Attributes/Link.php, src/Attributes/MediaType.php, src/Attributes/OpenApi.php, src/Attributes/OperationTrait.php, src/Attributes/ParameterTrait.php, src/Attributes/PathItem.php, src/Attributes/Property.php, src/Attributes/RequestBody.php, src/Attributes/Response.php, src/Attributes/Schema.php, src/Attributes/SecurityScheme.php, src/Attributes/Server.php, src/Attributes/ServerVariable.php, src/Attributes/Tag.php, src/Attributes/Xml.php, src/Attributes/XmlContent.php, tests/Samples/VendorExtensions.php
=> X typehint

docs/related-projects.md
- added laravel swagger project
- update lumen swagger project
=> add+update project links

src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/References.php
=> Handle '&' used for return by reference

composer.json, phpstan-baseline.neon, src/Analysers/TokenScanner.php
=> Dep updates

src/Analysers/ReflectionAnalyser.php
=> Set `uses` details on context

docs/guide/annotations.md
In particular show how to escape double quotes.
=> Add doc section about escaping in doctrine annotations

src/Attributes/Schema.php
=> Allow `Schema` attribute to be repeatable

src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Annotations/OpenApi.php, src/Context.php, src/Processors/AugmentProperties.php, src/Processors/AugmentSchemas.php, src/Processors/BuildPaths.php, src/Processors/Concerns/MergeTrait.php, src/Processors/MergeJsonContent.php, src/Processors/MergeXmlContent.php, src/Serializer.php, tests/Annotations/ComponentsTest.php, tests/Processors/ExpandClassesTest.php
Merge custom `AbstractAnnotation::_aux` property into `Context::generated`
=> Merge annotation `_aux` property with context `generated`

NOTICE
=> Adding copyright notice

src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/AbstractKeyword.php, tests/Fixtures/PHP/AnonymousFunctions.php, tests/Fixtures/PHP/Php8AttrMix.php, tests/Fixtures/PHP/Php8NamedArguments.php
Keep track of abstract functions and handle them the same as in interfaces.
Fixes #1365
=> Handle abstract functions

.github/workflows/build.yml, .github/workflows/code-style.yml, .github/workflows/security-checks.yml, src/Annotations/JsonContent.php, src/Annotations/Link.php, src/Annotations/MediaType.php, src/Context.php
=> Update for PHP 8.2

src/Annotations/AbstractAnnotation.php, src/Processors/AugmentSchemas.php, tests/Annotations/AbstractAnnotationTest.php, tests/Fixtures/Scratch/CustomAttributeSchema.php, tests/Fixtures/Scratch/CustomAttributeSchema.yaml, tests/Fixtures/Scratch/MergeTraits.php, tests/Fixtures/Scratch/ParameterContent.php
=> Consider the root annotation type when augmenting schemas

phpstan-baseline.neon, src/Analysis.php, src/Generator.php, src/Processors/AugmentParameters.php, src/Processors/AugmentProperties.php, src/Processors/AugmentRefs.php, src/Processors/AugmentSchemas.php, src/Processors/BuildPaths.php, src/Processors/CleanUnmerged.php, src/Processors/CleanUnusedComponents.php, src/Processors/DocBlockDescriptions.php, src/Processors/ExpandClasses.php, src/Processors/ExpandEnums.php, src/Processors/ExpandTraits.php, src/Processors/MergeIntoComponents.php, src/Processors/MergeIntoOpenApi.php, src/Processors/MergeJsonContent.php, src/Processors/MergeXmlContent.php, src/Processors/OperationId.php, src/Processors/ProcessorInterface.php
Prepare a soft migration from callable to `ProcessorInterface` for processors
=> Add (optional) ProcessorInterface and update method signatures

src/Processors/AugmentProperties.php
Fixes the issue mentioned on https://github.com/zircote/swagger-php/pull/1391#issuecomment-1383826332
=> Fix refs automatically set to nullable

src/Analysis.php
Alternative to #1315
Related to #1311
=> Make schema lookup work for custom schema implementations

src/Processors/CleanUnusedComponents.php, src/Processors/Concerns/CollectorTrait.php
=> Fix spelling of `oneOf`

docs/guide/faq.md
Fixes #1394 - well, at least documents the behaviour
=> Add section about BC issues with multiple consecutive docblocks

src/Generator.php, src/Loggers/ConsoleLogger.php, tests/ExamplesTest.php, tests/OpenApiTestCase.php
=> Add debug logging of files being analysed

src/Analysis.php, tests/Fixtures/Scratch/ThirdPartyAnnotation.php, tests/Fixtures/Scratch/ThirdPartyAnnotation.yaml
=> Make `isRoot()` call on annotation safe

src/Analysers/AttributeAnnotationFactory.php, tests/Fixtures/Scratch/PromotedProperty.php, tests/Fixtures/Scratch/PromotedProperty.yaml
=> Handle promoted property inline docblocks for attributes

tests/Fixtures/Scratch/CustomAttributes.php, tests/Fixtures/Scratch/CustomAttributes.yaml
=> Add scratch test using custom attributes

src/Processors/AugmentProperties.php, src/Processors/Concerns/DocblockTrait.php, tests/Fixtures/Scratch/Docblocks.php, tests/ScratchTest.php
=> Fix `@var` docblock parsing

src/Annotations/RequestBody.php, src/Attributes/RequestBody.php
The same as #1408 but with code style fixed
=> Add MediaType as possible type to RequestBody

src/Annotations/PathItem.php, src/Attributes/PathItem.php, tests/Annotations/AbstractAnnotationTest.php
=> Add missing `description` property to `PathItem`

src/Attributes/RequestBody.php
=> Make `RequestBody` attribute IS_REPEATABLE

Examples/using-refs/OpenApiSpec.php
=> Improve example of using global parameter references

README.md
* Update status badge from Travis to GH Action
* Add install version ^2
* Remove Bitdeli badge (broken link)
=> Update README (v2)

src/Processors/OperationId.php, tests/Fixtures/Scratch/AttributeInheritance.yaml, tests/Fixtures/Scratch/ClassRef.yaml, tests/Fixtures/Scratch/CustomAttributeSchema.yaml, tests/Fixtures/Scratch/CustomAttributes.yaml, tests/Fixtures/Scratch/CustomPropertyAttribute.yaml, tests/Fixtures/Scratch/Docblocks.yaml, tests/Fixtures/Scratch/DuplicateRef.yaml, tests/Fixtures/Scratch/MergeTraits.yaml, tests/Fixtures/Scratch/MergeTraitsExtended.yaml, tests/Fixtures/Scratch/MultiplePathsForEndpoint.yaml, tests/Fixtures/Scratch/NestedAdditionalProperties.yaml, tests/Fixtures/Scratch/NestedSchema.yaml, tests/Fixtures/Scratch/Nullable.yaml, tests/Fixtures/Scratch/PromotedProperty.yaml, tests/Fixtures/Scratch/PropertyInheritance.yaml, tests/Fixtures/Scratch/ThirdPartyAnnotation.yaml, tests/ScratchTest.php
=> Generate operationId for class endpoints

src/Annotations/Schema.php, src/Annotations/ServerVariable.php, src/Attributes/AdditionalProperties.php, src/Attributes/Items.php, src/Attributes/JsonContent.php, src/Attributes/Property.php, src/Attributes/Schema.php, src/Attributes/ServerVariable.php, src/Attributes/XmlContent.php, tests/Annotations/AttributesSyncTest.php, tests/Fixtures/Scratch/Nullable.php, tests/Fixtures/Scratch/Nullable.yaml
=> Fix typehint to make `null` a valid enum value

src/Processors/AugmentProperties.php, tests/Fixtures/Scratch/Docblocks.php, tests/Fixtures/Scratch/Docblocks.yaml
Th PR address https://github.com/zircote/swagger-php/issues/1553 topic
=> integer ranges support

src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Context.php, src/Generator.php, tests/ContextTest.php
=> Ensure all annotations added to `Analysis` have a root context

composer.json, phpstan-baseline.neon, src/Analysers/TokenScanner.php, tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/namespaces3.php, tests/Fixtures/Scratch/ExclusiveMinMax.php, tests/Fixtures/Scratch/ExclusiveMinMax3.0.0.yaml, tests/Fixtures/Scratch/ExclusiveMinMax3.1.0.yaml, tests/Fixtures/Scratch/NullRef.php, tests/Fixtures/Scratch/ParameterContent.php, tests/Fixtures/Scratch/ThirdPartyAnnotation.php, tests/Fixtures/Scratch/ThirdPartyAnnotation3.0.0.yaml, tests/Fixtures/Scratch/ThirdPartyAnnotation3.1.0.yaml
Reverts zircote/swagger-php#1597
=> Revert "Re-implement `TokenScanner` using nikic/php-parser"

src/Analysers/ReflectionAnalyser.php, src/Analysis.php, src/Annotations/AbstractAnnotation.php, src/Annotations/OpenApi.php, src/Generator.php, src/OpenApiException.php, src/Pipeline.php, src/Processors/ExpandEnums.php, src/Serializer.php, src/Util.php
=> Introduce `OpenApiException`

src/Generator.php
Also adds syntax to congigure config array values
=> Fix: Pass CLI config options into `Generator`

Examples/swagger-spec/petstore/petstore.yaml, Examples/using-refs/using-refs.yaml, src/Processors/AugmentTags.php
=> Strip duplicate tags in `AugmentTags`

src/Analysers/AttributeAnnotationFactory.php, tests/Fixtures/Scratch/PromotedProperty.php, tests/Fixtures/Scratch/PromotedProperty3.0.0.yaml, tests/Fixtures/Scratch/PromotedProperty3.1.0.yaml
Follow up for #1619 and fixing #1419
=> Preserve docblocks for consecutive promoted properties

src/Processors/AugmentTags.php
=> Use array_search strict comparison

src/Processors/AugmentTags.php, tests/Fixtures/SurplusTag.php, tests/Processors/AugmentTagsTest.php
=> Deduplicate declared tags

docs/.vitepress/theme/custom.css, docs/reference/annotations.md, docs/reference/attributes.md, docs/reference/processors.md, src/Annotations/PathParameter.php, tools/src/Docs/RefGenerator.php
=> Add required: yes/no to reference docs

docs/guide/generating-openapi-documents.md, docs/index.md
=> Reference `openapi` CLI tools as `./vendor/bin/openapi`

docs/guide/generating-openapi-documents.md
=> Add example of using `-b` to basic CLI example

docs/guide/faq.md, docs/guide/under-the-hood.md, phpstan-baseline.neon
=> Expand on using the `-b` option for single files

bin/openapi
=> Remove use of deprecated `E_STRICT`

docs/examples/specs/api/annotations/ProductController.php, docs/examples/specs/api/api-3.0.0.yaml, docs/examples/specs/api/api-3.1.0.yaml, docs/examples/specs/api/mixed/ProductController.php, docs/examples/specs/petstore/petstore-3.0.0.yaml, docs/examples/specs/petstore/petstore-3.1.0.yaml, src/Annotations/Flow.php, src/Annotations/OpenApi.php, src/Attributes/Flow.php, src/Attributes/OpenApi.php, src/Attributes/ParameterTrait.php, src/Processors/AugmentParameters.php, tests/Annotations/OpenApiTest.php, tests/ScratchTest.php
=> Improve docblocks

tests/Fixtures/Scratch/DynamicEnumCase.php, tests/Fixtures/Scratch/DynamicEnumCase3.0.0.yaml, tests/Fixtures/Scratch/DynamicEnumCase3.1.0.yaml
=> Add scratch for dynamic enum case values

docs/reference/annotations.md, docs/reference/attributes.md, docs/reference/processors.md, src/Processors/Concerns/AnnotationTrait.php, src/Processors/PathFilter.php
=> Add option to turn off recursive cleanup in `PathFilter`

src/Attributes/ParameterTrait.php, tests/Fixtures/Scratch/PathParameter.php, tests/Fixtures/Scratch/PathParameter3.0.0.yaml, tests/Fixtures/Scratch/PathParameter3.1.0.yaml
=> Preserve preset `required: true` for `OAT\PathParameter`

src/Processors/AugmentParameters.php, tests/Fixtures/RequestUsingAttribute.php, tests/Processors/AugmentParametersTest.php
For Fix nativeTypeMap not execd in PathParameter only used with no docblock
=> Fix parameter type

src/Processors/AugmentProperties.php, tests/Fixtures/Scratch/Nullable.php, tests/Fixtures/Scratch/Nullable3.0.0.yaml, tests/Fixtures/Scratch/Nullable3.1.0.yaml
=> Favour annotation nullable over native

src/Analysers/AttributeAnnotationFactory.php, tests/Fixtures/Scratch/Nullable.php, tests/Fixtures/Scratch/Nullable3.0.0.yaml, tests/Fixtures/Scratch/Nullable3.1.0.yaml
=> Favour promoted property annotation nullable over native

src/Annotations/Components.php, src/Context.php, src/Processors/ExpandEnums.php, tests/Annotations/OpenApiTest.php
=> Ensure `Context` can be serialized

src/Context.php, tests/ContextTest.php
=> Improve `Context::__serialize`

tests/Analysers/TokenScannerTest.php, tests/Fixtures/PHP/MultiNamespace.php
Confirm that #1795 is fixed in v5
=> Add a single-file-multi-namespace fixture + test

phpstan-baseline.neon, src/Processors/AugmentParameters.php, src/Processors/AugmentProperties.php, src/Processors/Concerns/DocblockTrait.php, src/Processors/DocBlockDescriptions.php, tests/Processors/AugmentParametersTest.php, tests/Processors/DocBlockDescriptionsTest.php
Includes some renaming of methods, so not fully BC.
=> Minor docblock cleanup/refactor
